# Конфигурация golangci-lint для проекта PR Reviewer Assignment Service
# Документация: https://golangci-lint.run/usage/configuration/

version: 2

# Настройки запуска линтера
run:
  # Максимальное время выполнения линтера
  timeout: 5m

  # Проверять тестовые файлы (_test.go)
  tests: true

  # Версия Go для проверки синтаксиса
  go: '1.25'

  # Директории, которые будут пропущены при проверке
  skip-dirs:
    - vendor
    - internal/generated

  # Файлы, которые будут пропущены
  skip-files:
    - ".*\\.pb\\.go$"  # Protobuf сгенерированные файлы

# Настройки вывода результатов
output:
  # Формат вывода: цветной с номерами строк
  format: colored-line-number

  # Показывать проблемные строки кода
  print-issued-lines: true

  # Показывать имя линтера, который нашёл проблему
  print-linter-name: true

  # Сортировать результаты по файлам и строкам
  sort-results: true

# Список включённых линтеров
linters:
  # Отключаем все линтеры по умолчанию, включаем только нужные
  disable-all: true

  enable:
    # ============================================
    # Обработка ошибок
    # ============================================
    - errcheck          # Проверяет, что все ошибки обработаны
    - errorlint         # Проверяет правильность сравнения и обёртывания ошибок
    - errname           # Проверяет соответствие имён ошибок конвенциям Go
    - nilerr            # Находит подозрительные возвраты nil вместо ошибки
    - nilnil            # Находит возвраты (nil, nil) - подозрительный паттерн

    # ============================================
    # Статический анализ
    # ============================================
    - govet             # Стандартный линтер от команды Go (go vet)
    - staticcheck       # Расширенный статический анализ кода
    - unused            # Находит неиспользуемый код (переменные, функции, импорты)
    - unparam           # Находит неиспользуемые параметры функций

    # ============================================
    # Безопасность
    # ============================================
    - gosec             # Проверка безопасности (SQL injection, криптография, утечки)
    - sqlclosecheck     # Проверяет закрытие всех SQL ресурсов (rows, stmt, conn)

    # ============================================
    # Производительность
    # ============================================
    - prealloc          # Находит места, где можно предварительно выделить память для слайсов
    - unconvert         # Находит ненужные конвертации типов

    # ============================================
    # Сложность кода
    # ============================================
    - gocyclo           # Измеряет цикломатическую сложность (количество путей выполнения)
    - gocognit          # Измеряет когнитивную сложность (насколько сложно понять код)
    - nestif            # Находит излишнюю вложенность if-блоков

    # ============================================
    # Стиль кода
    # ============================================
    - gocritic          # Многофункциональный линтер для улучшения качества кода
    - goconst           # Находит строки, которые можно вынести в константы
    - whitespace        # Находит лишние пустые строки
    - mirror            # Проверяет правильность использования bytes/strings пакетов
    - predeclared       # Запрещает названия, схожие с предопределёнными идентификаторами Go
    - contextcheck      # Проверяет правильную передачу context.Context

    # ============================================
    # Орфография и опечатки
    # ============================================
    - misspell          # Находит опечатки в комментариях и строках

# Настройки конкретных линтеров
linters-settings:
  # Проверка обработки ошибок
  errcheck:
    # Функции, ошибки которых можно игнорировать
    exclude-functions:
      # Игнорируем ошибку при закрытии логгера (не критично)
      - (*go.uber.org/zap.SugaredLogger).Sync

  # Стандартный линтер Go
  govet:
    # Включить все анализаторы go vet
    enable-all: true
    disable:
      # Отключаем shadow (проверка затенения переменных) - слишком строго
      - shadow

  # Цикломатическая сложность
  gocyclo:
    # Минимальная сложность для предупреждения (15 - умеренная сложность)
    min-complexity: 15

  # Когнитивная сложность
  gocognit:
    # Минимальная когнитивная сложность для предупреждения (20 - умеренная)
    min-complexity: 20

  # Поиск строк для констант
  goconst:
    # Минимальная длина строки для предложения вынести в константу
    min-len: 3
    # Минимальное количество повторений строки для предложения
    min-occurrences: 3

  # Проверка орфографии
  misspell:
    # Локаль для проверки (US English)
    locale: US

  # Вложенность if-блоков
  nestif:
    # Минимальная вложенность для предупреждения (4 уровня)
    min-complexity: 4

  # Проверка безопасности
  gosec:
    # Исключаемые правила
    excludes:
      # G104 - игнорируем ошибки (дублирует errcheck)
      - G104
    # Настройки правил безопасности
    config:
      # G201/G202 - SQL injection проверка (уровень строгости 99)
      G201: "99"  # SQL statement construction
      G202: "99"  # SQL string concatenation

  # Многофункциональный линтер
  gocritic:
    # Включённые категории проверок
    enabled-tags:
      - diagnostic   # Диагностические проверки
      - style        # Стилистические проверки
      - performance  # Проверки производительности
      - experimental # Экспериментальные проверки
      - opinionated  # Проверки с субъективными рекомендациями
    # Отключённые проверки
    disabled-checks:
      - whyNoLint    # Не требуем объяснений для nolint
      - hugeParam    # Разрешаем большие параметры (для domain объектов)

  # Предварительное выделение памяти
  prealloc:
    simple: true      # Простые случаи (make([]T, 0, n))
    range-loops: true # Циклы range
    for-loops: true   # Обычные циклы for

# Настройки обработки найденных проблем
issues:
  # Лимиты на количество проблем
  max-issues-per-linter: 50  # Максимум проблем от одного линтера
  max-same-issues: 3          # Максимум одинаковых проблем

  # Показывать все проблемы (не только новые)
  new: false

  # Правила исключений
  exclude-rules:
    # Тестовые файлы - разрешаем более сложный код
    - path: _test\.go
      linters:
        - gocyclo   # Разрешаем более сложные функции в тестах
        - gocognit  # Разрешаем более высокую когнитивную сложность
        - nestif    # Разрешаем большую вложенность

    # SQL миграции - не проверяем
    - path: migrations/
      linters:
        - all  # Отключаем все линтеры для миграций

  # Не использовать дефолтные исключения
  exclude-use-default: false
  # Учитывать регистр при исключениях
  exclude-case-sensitive: false

